### PR TITLE
The old form implementation should die

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by dmaclay** [comment]
ok :+1:  ... only deletes & tests still pass

**Comment by smn** [comment]
If I land this your multipoll app in Go will be very sad.

**Comment by hodgestar** [comment]
Is there a better form implementation somewhere? I think the survey app would be sad too. I actually think the forms do below in vxpolls since they're tightly linked to the poll configuration data structures.

**Comment by smn** [comment]
The surveys app has been updated to use the new polls a few weeks ago already.

**Comment by hodgestar** [comment]
I still see:

```
$ ack-grep "from.*vxpolls.*forms" go/apps/ 
go/apps/surveys/views.py
16:from vxpolls.content import forms

go/apps/multi_surveys/views.py
15:from vxpolls.content import forms
```

Am I missing something?

**Comment by hodgestar** [comment]
Ah. I see surveys only use the few methods that are left over after deleting the other things. I guess multi surveys just needs to be updated.

**Pull request closed without merging**
