### PR TITLE
Feature/vumigo 162 the session manager is not using the prefixes when used by vxpolls

### PR DESCRIPTION
**Pull request by dmaclay**
just needed a sub_manager to restore the prefix that used to be passed to the session manager

### CODE REVIEW

**Comment by hodgestar** [comment]
Just want to double-check that you're expecting keys like "<prefix>:session:session:<user_id>" because the session manager appends a "session" of its own. If you're not, you probably just want `sub_manager(self.r_prefix)`.

Otherwise :+1:. I'm a bit against the test check for `_key_prefix` because it's underscored. There are ways around that but I'm not sure they're any better so I'm happy for that to stay as it is.

**Comment by dmaclay** [comment]
Based on the actual data in our live go deploy
keys that should start with: 
    vumigo:vxpolls:session:session: 
just start with: 
    vumigo:session:

I personally don't see the point of the double "session" but it's what our current "correct" keys use.

**Comment by jerith** [comment]
I'd rather fix the doubled `session` prefix and rename existing keys. Also, the fact that we have one thing using one prefix and another using another means we're creating a session manager in multiple places. I don't think we should be doing that...

**Comment by hodgestar** [comment]
I think the doubled prefix is actually fine, if just a bit odd. It makes sense to put the session manager in its own sub-manager. That the session manager then adds its own prefix is a bit odd, but I don't think we should change that just for this.

Creating the session manager in two places is a bit unavoidable at the moment -- one is created in Django views, the other in a Vumi worker.

This is a bug fix, not a general clean-up, let's try keep the changes contained and open new tickets for clean-up if  anyone feels particularly strongly about it.

**Comment by jerith** [comment]
The session manager adds its own prefix so that the things using it don't have to. Session information is supposed to be transient and self-contained, so nothing outside the session manager should touch it directly.

On that note, I'm really surprised that we're using the session manager in Django views. If we need to get at data that's stored in sessions through the web UI, it probably shouldn't be stored in sessions.

**Comment by dmaclay** [comment]
actually the two prefix versions is not two concurrent session managers, but pre vs. post redeploy session data

**Comment by hodgestar** [comment]
:+1:

**Comment by smn** [comment]
:+1:

**Comment by smn** [comment]
@dmaclay do we have a script ready to do key renaming where necessary?

**Pull request merged**
